[workspace]
members = ["clients/apps/rust", "clients/libs/rust", "server", "lib", "clients/tests/rust", "token-server-v2"]
exclude = ["clients/apps/kotlin", "clients/apps/nodejs", "clients/apps/react-app", "clients/libs/nodejs", "docs", "enclave", "lockbox", "explorer", "keylistCron", "wasm"]
resolver = "2"
