services:

  esplora:
    image: blockstream/esplora
    container_name: esplora-container
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8094:80"
    volumes:
      - ./data_bitcoin_regtest:/data
    environment:
      - CORS_ALLOW=*
    command: /srv/explorer/run.sh bitcoin-regtest explorer

  vault:
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=2bbz80mr1zm0tfrjwxyq7f48ofgky848
    ports:
      - "8200:8200"

  vault-init:
    image: curlimages/curl
    depends_on:
      - vault
    command: >
      sh -c '
        sleep 10 &&
        curl --header "X-Vault-Token: 2bbz80mr1zm0tfrjwxyq7f48ofgky848" \
             --header "Content-Type: application/json" \
             --request POST \
             --data '"'"'{"data": {"seed": "8b10a037120cf37441bd7623da2aa488c21889017ffb4f4d303b9dbcbada5bee"}}'"'"' \
             http://vault:8200/v1/secret/data/mercury-seed &&
        touch /tmp/healthy &&
        tail -f /dev/null
      '
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/healthy"]
      interval: 1s
      timeout: 1s
      retries: 30

  lockbox:
    image: mercurylayer/lockbox:latest
    depends_on:
      - db_lockbox
    environment:
      - LOCKBOX_DATABASE_URL=postgres://postgres:postgres@db_lockbox:5432/enclave
      - LOCKBOX_PORT=18080
      - KEY_MANAGER=filesystem
      - SEED_FILEPATH=/data/seed
    ports:
      - "18080:18080"
    volumes:
      - lockbox_seed_data:/data

  token-server-v2:
    build:
      context: .
      dockerfile: ./token-server-v2/Dockerfile
    container_name: mercurylayer-token-server-v2-1
    environment:
      PUBLIC_KEY_DESCRIPTOR: wpkh([656a457c/84'/1'/0']tpubDCTXiLu1wcqUwQK6QMPPUTBzbRjsqMABzCvd5vG22KGoA95cTG1VkszQQJyx24UP8KEJVKrKRDRtUPodHVV59CfNqUkXjKUagowHJVSWq4C/0/*)#vn0n5xcd
      BITCOIN_NETWORK: regtest
      ELECTRUM_SERVER: tcp://esplora:50001
      FEE: 10000
      CONFIRMATION_TARGET: 2
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db_server
      DB_PORT: 5432
      DB_NAME: mercury
    ports:
      - "8001:8001"
    depends_on:
      - esplora
      - db_server

  mercury-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: mercurylayer-mercury-server-1
    depends_on:
      - db_server
      - lockbox
      - token-server-v2
    environment:
      BITCOIN_NETWORK: regtest
      LOCKHEIGHT_INIT: 1000
      LH_DECREMENT: 10
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db_server
      DB_PORT: 5432
      DB_NAME: mercury
      BATCH_TIMEOUT: 20
      ENCLAVES: '[{"url": "http://lockbox:18080", "allow_deposit": true}]'
      NOSTR_INFO: '{
        "relay_server": "wss://relay.damus.io/", 
        "relay_interval": 15, 
        "nostr_privkey": "nsec17e0nvplcze4k7q9nazrw0k3aracwhg6vmuareewjp83ta89njw5spjcgzs", 
        "server_url": "http://mercury_server.xyz", 
        "location": "UK",
        "active": true,
        "onchain_payments": false,
        "ln_payments": true,
        "fee": 0.0001,
        "unit": "BTC"
        }'
      TOKEN_SERVER_URL: http://token-server-v2:8001
    ports:
      - "8000:8000"

  db_lockbox:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enclave
    ports:
      - "5433:5432"
    volumes:
      - postgres_lockbox_data:/var/lib/postgresql/data

  db_server:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercury
    ports:
      - "5432:5432"
    volumes:
      - postgres_server_data:/var/lib/postgresql/data

volumes:
  postgres_lockbox_data:
  postgres_server_data:
  lockbox_seed_data:
