version: '3.8'

services:
  lockbox:
    build:
      context: lockbox
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://mercurylayer:<PASSWORD>@<DB_HOST>:5432/enclave
      - PORT=18080
      - KEY_MANAGER=filesystem
  mercury-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - LOCKBOX_URL=http://lockbox:18080
      - BITCOIN_NETWORK=testnet
      - LOCKHEIGHT_INIT=1000
      - LH_DECREMENT=10
      - DB_USER=mercurylayer
      - DB_PASSWORD=<CHANGEME>
      - DB_HOST=<CHANGEME>
      - DB_PORT=5432
      - DB_NAME=mercury
    ports:
      - "8000:8000"
  token-server-v2:
    build:
      context: .
      dockerfile: ./token-server-v2/Dockerfile
    environment:
      - PUBLIC_KEY_DESCRIPTOR=wpkh([656a457c/84'/1'/0']tpubDCTXiLu1wcqUwQK6QMPPUTBzbRjsqMABzCvd5vG22KGoA95cTG1VkszQQJyx24UP8KEJVKrKRDRtUPodHVV59CfNqUkXjKUagowHJVSWq4C/0/*)#vn0n5xcd
      - BITCOIN_NETWORK=testnet
      - ELECTRUM_SERVER=tcp://esplora:50001
      - FEE=10000
      - CONFIRMATION_TARGET=2
      - DB_USER=mercurylayer
      - DB_PASSWORD=<CHANGEME>
      - DB_HOST=<CHANGEME>
      - DB_PORT=5432
      - DB_NAME=mercury
    ports:
      - "8001:8001"
  explorer:
    build:
      context: explorer
      dockerfile: Dockerfile
    ports:
      - "80:80"
