[package]
name = "mercury-server"
version = "0.2.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { workspace = true }
config = { workspace = true }
reqwest = { workspace = true }
rocket = { workspace = true }
sqlx = { workspace = true, features = [ "postgres", "chrono", "tls-rustls" ] }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
secp256k1-zkp = { workspace = true }
# secp256k1-zkp = { path = "../ss-rust-secp256k1-zkp", features = [ "rand-std", "bitcoin_hashes", "std" ] }
mercurylib = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
nostr-sdk = { workspace = true }
