[package]
name = "mercurylib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "mercurylib"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
required-features = ["bindings"]

[dependencies]
bitcoin = { workspace = true }
bip39 = { workspace = true }
bech32 = { workspace = true }
ecies = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
secp256k1-zkp = { workspace = true }
uniffi = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = []
bindings = ["uniffi", "uniffi/cli"]
